#------------------------------------------------------------------------------#
#--------------------         Server Configuration         --------------------#
#------------------------------------------------------------------------------#

#---------------------------------   Manual   ---------------------------------#
#------------------------------------------------------------------------------#

#                 #
# --- Globals --- #
#                 #

# If true, the server starts a file server located at `tcp_server.public_dir`
# `production`: = `bool`

#                                          #
# --- Pacstall Programs ( Repository ) --- #
#                                          #

# Repository URL for the pacstall repository.
# `pacstall_programs.url`              = `string`

# Temporary dir path to store scripts. If the dir doesn't exist, it gets created
# `pacstall_programs.tmp_dir`          = `string`

#  How often to pull git commits. Time in seconds
# `pacstall_programs.update_interval`  = `int`

#  Maximum number of open files during the package scanning
# `pacstall_programs.max_open_files`   = `uint8`

#                    #
# --- TCP Server --- #
#                    #

# What port to listen on
# `tcp_server.port`        = `uint16`

# Directory containing all public html files
# `tcp_server.public_dir`  = `string` 

#                       #
# --- Feature Flags --- #
#                       #

# Syntax for the pacstall cli
# `feature_flags.old_syntax` = `bool`

# `feature_flags.package_details_page.last_updated`     = `bool`
# `feature_flags.package_details_page.votes`            = `bool`
# `feature_flags.package_details_page.popularity`       = `bool`
# `feature_flags.package_details_page.install_protocol` = `bool`
# `feature_flags.package_details_page.comments`         = `bool`

#                 #
# --- Logging --- #
#                 #

# Uses dynamic progress bars and colors if enabled
# `logging.fancy_logs` = `bool`
# `logging.log_level`  = `debug` | `info` | `warn` | `error`

#------------------------------------------------------------------------------#


production = false

[pacstall_programs]
url             = "https://github.com/pacstall/pacstall-programs"
tmp_dir         = "./tmp"
update_interval = 900
max_open_files  = 100

[tcp_server]
port        = 3300
public_dir  = "../client/dist"

[feature_flags]
old_syntax = true

[feature_flags.package_details_page]
last_updated     = false
votes            = false
popularity       = false
install_protocol = false
comments         = false

[logging]
log_level = "debug"
fancy_logs = false

#------------------------------------------------------------------------------#